### PR TITLE
fix: update rnpm

### LINKED ISSUE #64: update `rnpm` to react-native config
Not sure where we saw this, but when Chris and I were using the template, we saw it mentioned (I think in Metro Bundler) that we needed to update `rnpm` to use a `react-native.config.json` file instead of whatever we were previously using.

### PR DESCRIPTION
**Pull request by jsjoeio**
Updates the `rnpm` config based on the newest version of React Native. Instead of adding it to the `package.json`, [it is recommended](https://github.com/react-native-community/cli/blob/master/docs/configuration.md#apps) that you add it to a `react-native.config.js` file.

## Changes
- add helper function `copyFile`
- remove `rnpm.json` file
- create `react-native.config.js` file
- update setup to copy file into root of directory.

## Screenshots
It works!
image

And the app still runs
image

## Checklist
- [ ] Automated tests
- [X] Creating a new project still works
- [ ] Added docs

Fixes #64

### CODE REVIEW

**Comment by cball** [comment]
@jsjoeio Could we just add this file to the root of the project and lean on `react-native init` to copy for us? Similar to this https://github.com/echobind/react-native-template-echobind/blob/master/rn-cli.config.js

**Comment by jsjoeio** [comment]
> @jsjoeio Could we just add this file to the root of the project and lean on `react-native init` to copy for us? Similar to this https://github.com/echobind/react-native-template-echobind/blob/master/rn-cli.config.js

@cball that's too simple! we must overengineer everything 😜 

Great idea - I didn't even think of doing it that way. I'll refactor.

**Comment by cball** [comment]
All good! It's not really an obvious direction if you're new to it

**Comment by jsjoeio** [comment]
Oh no! Should have tested this in last PR - I will fix in this one. 

image

**Comment by jsjoeio** [comment]
Success! 
image

**Pull request merged**
